spring:
  profiles:
    active: local
  datasource:
    #url: jdbc:mariadb://localhost:3306/minair
    url: jdbc:mariadb://minair-database.cllkjs3lli6y.us-east-2.rds.amazonaws.com:3306/minair
    username: min
    password: alsdud6038
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  #mvc:
  #  hiddenmethod:
  #    filter:
  #      enabled: true

  jpa:
    #hibernate:
      #ddl-auto: create
    properties:
      hibernate:
#  show_sql: true
      format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  port: 80
  compression:
    enabled: true
