spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3306/minair
    username: min
    password: alsdud6038
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  #mvc:
   # static-path-pattern: /resources/static/**

  jpa:
    #hibernate:
      #ddl-auto: create
    properties:
      hibernate:
#  show_sql: true
      format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

property:
  pageNum: 1